# Generated by Django 6.0.1 on 2026-01-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(help_text='Ex: USTB, UJKZ, VESSA', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('filiere', models.CharField(choices=[('GL', 'Génie Logiciel'), ('RIT', 'Réseaux et Informatique de Gestion'), ('MIAGE', 'Méthodes Informatiques Appliquées à la Gestion'), ('OTHER', 'Autre')], default='GL', max_length=10, verbose_name='Filière académique')),
                ('level', models.IntegerField(default=1, help_text="Année d'étude actuelle (ex: 1 pour L1, 3 pour L3)", verbose_name='Niveau')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.university')),
            ],
        ),
    ]
