# Generated by Django 6.0.1 on 2026-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(help_text='Ex: USTB, UJKZ, VESSA', max_length=20, unique=True),
        ),
    ]
